# Generated by Django 2.2.7 on 2019-11-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20191117_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': 'Room Type'},
        ),
    ]
