# Generated by Django 2.2.7 on 2019-12-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippets',
            name='gender',
            field=models.CharField(choices=[('male', 'boys'), ('shmale', 'girls'), ('other', 'alien')], default='GENDER_MALE', max_length=10),
        ),
    ]
